In [0]:
#Name: Prakash Kumar
#Roll: 161210033
#lab 1 : Dated 11/01/19

###Question:  You have the results of various bee species. The number of bees observed was as follows:

####BuffTail: 10 1 37 5 12

#### Garden bee: 8 3 19 6 4

####Red tail: 18 9 1 2 4

####Honeybee: 12 13 16 9 10

####Carder bee: 8 27 6 32 23

In [0]:
# We are importing pandas library to create DataFrame.
import pandas as pd
import numpy as np

####a) Make simple numeric vector. Join the bee vectors together to make a data frame.

####Each row of the resulting data frame relates to a specific plant so you could assign names to the rows.

####The plant names are Thistle, Vipers Bugloss, Golden Rain, Yellow Alfalfa, and blackberry.

In [0]:
# We are creating the five columns of bees species as lists
data= {
    'BuffTail'   : [10,1,37,5,12],
    'Garden bee' : [8, 3, 19, 6, 4],
    'Red tail'   : [18, 9, 1, 2, 4],
    'Honeybee'   : [12, 13, 16, 9, 10],
    'Carder bee' : [8, 27, 6, 32, 23]    
}

In [0]:
#Making dataframe df1 using dict 
df1=pd.DataFrame(data,index=['Thistle','Vipers Bugloss','Golden Rain','Yellow Alfalfa','blackberry'],
                columns=['BuffTail','Garden bee','Red tail','Honeybee','Carder bee'])
df1

BuffTail  Garden bee  Red tail  Honeybee  Carder bee
Thistle               10           8        18        12           8
Vipers Bugloss         1           3         9        13          27
Golden Rain           37          19         1        16           6
Yellow Alfalfa         5           6         2         9          32
blackberry            12           4         4        10          23

 #### b) Make the matrix object from the original data.

In [0]:
# Making matrix using numpy 
matrix=df1.values
print(matrix)

[[10  8 18 12  8]
 [ 1  3  9 13 27]
 [37 19  1 16  6]
 [ 5  6  2  9 32]
 [12  4  4 10 23]]


####  c) Display the data for the Blackberry only.

In [0]:
#Passing blackberry column
df1.loc[["blackberry"]]


BuffTail  Garden bee  Red tail  Honeybee  Carder bee
blackberry        12           4         4        10          23

####d) Display the data for Golden rain and yellow alfalfa.

In [0]:
#Passing Golden Rain and Yellow Afalfa columns
df1.loc[["Golden Rain","Yellow Alfalfa"]]

BuffTail  Garden bee  Red tail  Honeybee  Carder bee
Golden Rain           37          19         1        16           6
Yellow Alfalfa         5           6         2         9          32


#### e) Display the data for the red tail bee only.

In [0]:
#Passing Red tail column
df1["Red tail"]

Thistle           18
Vipers Bugloss     9
Golden Rain        1
Yellow Alfalfa     2
blackberry         4
Name: Red tail, dtype: int64


####f) Reorder the data so that the bufftail column is sorted in decreasing abundance.

In [0]:
#Using sort_values function and pass column Bufftail as argument
#And taking ascending order as false.
print(df1.sort_values(by='BuffTail',ascending=False))

                BuffTail  Garden bee  Red tail  Honeybee  Carder bee
Golden Rain           37          19         1        16           6
blackberry            12           4         4        10          23
Thistle               10           8        18        12           8
Yellow Alfalfa         5           6         2         9          32
Vipers Bugloss         1           3         9        13          27
