###Prakash Kumar
###161210033
###Lab 2 Dated: 18/01/19

### Q1. Create a data item sample:

In [0]:
import numpy as np
a=np.array([2,4,7,1,9])

In [0]:
print("Array taken is :")
print(a)

Array taken is :
[2 4 7 1 9]


####a) Determine the largest value in the sample.

In [0]:
#numpy.max() returns the maximum element of data sample
print(np.max(a))

9


####b) Determine the smallest value in the sample.

In [0]:
#numpy.min() returns the minimum element of data sample
print(np.min(a))

1


####c) List out how many items are in the sample.

In [0]:
#array_name.size() returns the no. of eleemts in array
print(a.size)

5


####d) Display the average of the sample.

In [0]:
#numpy.mean() returns average of data sample
print(np.mean(a))

4.6


####e) Work out the standard deviation of the sample.

In [0]:
#numpy.std() returns standard deviation of data sample
print(np.std(a))

3.006659275674582


###Q2. Suppose a={(1,1,3),(5,2,6),(-2,-1,-3)}

In [0]:
#numpy.array() is used to create array
a = np.array([[1, 1, 3], [5, 2, 6], [-2, -1, -3]])
print(a)

[[ 1  1  3]
 [ 5  2  6]
 [-2 -1 -3]]


####a) check that a^3(a pow 3)=0 where 0 is a 3*3 matrix with every entry equal to 0

In [0]:
#numpy.linalg.matrix_power(M,n) is used to raise a square matrix to the (integer) power n.
b=np.linalg.matrix_power(a, 3)

#Creating 3*3 zero matrix
c = np.zeros([3, 3]) 

#numpy.array_equal(a1, a2) returns True if two arrays have the same shape and elements, False otherwise.
if (np.array_equal(b,c)):
  print("Yes!!! a^3(a pow 3)=0")
else:
  print("No!!! a^3(a pow 3)!=0")

Yes!!! a^3(a pow 3)=0


####b) replace the 3rd column of a by the sum of the 2nd and 3rd column.

In [0]:
#a[x:y] returns the element of a in the x row, y column.
a[:,2] = a[:,1] + a[:,2]
print(a)

[[ 1  1  4]
 [ 5  2  8]
 [-2 -1 -4]]


###Q3.Create the following pattern matrix : 
#### {(0,1,2,3,4),(1,2,3,4,5),(2,3,4,5,6),(3,4,5,6,7),(4,5,6,7,8)}

In [0]:
# range() returns a sequence of numbers, starting from 0 by default, 
# and increments by 1 (by default), and ends at a specified number
np.array([[int(i) for i in range(k, k+5)] for k in range(4)])

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])